# Dockerfile.worker
FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04

RUN apt-get update && apt-get install -y python3-pip git ffmpeg
WORKDIR /workspace

# Install python deps
COPY requirements.txt .
RUN pip3 install -r requirements.txt

# Copy worker
COPY worker_local.py /workspace/worker_local.py

CMD ["python3", "/workspace/worker_local.py"]
